{% set name = "streamlit-folium" %}
{% set version = "0.18.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/streamlit_folium-{{ version }}.tar.gz
  sha256: 193fc7ec301b59e9a8b3a37bc7a33ebe62985e161173a19465a277e7cbc8fc4f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - folium >=0.13,!=0.15
    - streamlit >=1.13
    - python >=3.7
    - branca
    - jinja2

test:
  imports:
    - streamlit_folium
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/randyzwitch/streamlit-folium
  summary: Render Folium objects in Streamlit
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - randyzwitch
