{% set name = "streamlit-folium" %}
{% set version = "0.25.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/streamlit_folium-{{ version }}.tar.gz
  sha256: 066a769312e3d2aff6c69763cdd78e4cc7e1ca925ee47629a6561524edc860df

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - uv-build
  run:
    - folium >=0.13,!=0.15
    - streamlit >=1.35
    - python >={{ python_min }}
    - branca
    - jinja2

test:
  imports:
    - streamlit_folium
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/randyzwitch/streamlit-folium
  summary: Render Folium objects in Streamlit
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - randyzwitch
