{% set name = "streamlit-folium" %}
{% set version = "0.26.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/streamlit_folium-{{ version }}.tar.gz
  sha256: 9d744d39aa2493b81ca05b9031e0cb2486fd4d9625b7eac97a4465cf886ec87f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - uv-build
  run:
    - folium >=0.13,!=0.15
    - streamlit >=1.35
    - python >={{ python_min }}
    - branca
    - jinja2

test:
  imports:
    - streamlit_folium
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/randyzwitch/streamlit-folium
  summary: Render Folium objects in Streamlit
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - randyzwitch
