{% set name = "streamlit-folium" %}
{% set version = "0.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/streamlit_folium-{{ version }}.tar.gz
  sha256: 4cb86097fd60f409117a57a66b26c736ac003a79665a5a30a2aa9495e44adf24

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - folium ==0.11
    - python >=3.6
    - streamlit >=0.63

test:
  imports:
    - streamlit_folium
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/randyzwitch/streamlit-folium
  summary: Render Folium objects in Streamlit
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - randyzwitch
