{% set name = "streamlit-folium" %}
{% set version = "0.25.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/streamlit_folium-{{ version }}.tar.gz
  sha256: f32eb51c1958705030e15045a38edaf9c046d6de5e6587e64190251466a4a006

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - folium >=0.13,!=0.15
    - streamlit >=1.35
    - python >={{ python_min }}
    - branca
    - jinja2

test:
  imports:
    - streamlit_folium
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/randyzwitch/streamlit-folium
  summary: Render Folium objects in Streamlit
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - randyzwitch
