{% set name = "streamlit-folium" %}

{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/streamlit_folium-{{ version }}.tar.gz
  sha256: 474fd84cbf53696d64624a67c6ea7edf7c7ddd226a4c5b6ef721f3303267ff63

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - folium >=0.11,!=0.12.0
    - python >=3.6

test:
  imports:
    - streamlit_folium
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/randyzwitch/streamlit-folium
  summary: Render Folium objects in Streamlit
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - randyzwitch
